# Generated by Django 2.1.dev20171104145028 on 2017-11-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0002_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='config',
            options={'verbose_name_plural': 'Config'},
        ),
        migrations.AddField(
            model_name='config',
            name='tagline',
            field=models.CharField(blank=True, default='', help_text='Optional pithy descriptive phrase', max_length=140),
        ),
        migrations.AlterField(
            model_name='config',
            name='title',
            field=models.CharField(help_text='To be displayed in page header and as part of HTML title tag', max_length=140, verbose_name='Site Title'),
        ),
    ]
