# Generated by Django 2.1.dev20171104145028 on 2017-11-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0003_auto_20171117_0718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='title',
        ),
        migrations.AddField(
            model_name='config',
            name='site_title',
            field=models.CharField(default='Arbitrary Site Title', help_text='To be displayed in page header and as part of HTML title tag', max_length=140),
        ),
    ]
