# Generated by Django 2.1.dev20171104145028 on 2017-12-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0012_config_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='moderation_email',
            field=models.CharField(default='Johnny Cash <johnny@example.com>', help_text='Comment moderation emails will be sent TO this address.            Should be a real, reachable email.', max_length=100),
        ),
    ]
