# Generated by Django 2.0 on 2018-01-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0015_auto_20171224_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique_for_date='pub_date'),
        ),
    ]
