# Generated by Django 2.0.1 on 2018-01-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0023_config_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='site_title',
        ),
    ]
