# Generated by Django 2.0.1 on 2018-01-23 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0028_auto_20180122_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Each category must be associated with a blog / named news site.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.Config'),
        ),
    ]
