# Generated by Django 2.1.dev20171104145028 on 2017-11-12 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('trashed', models.BooleanField(default=False, help_text='Trashed posts are removed from views but not deleted. For safety, Trash rather than Delete.')),
                ('pub_date', models.DateTimeField(blank=True, help_text="If present, overrides automatic 'created' datetime and will not be published until.", null=True)),
                ('ptype', models.CharField(choices=[('post', 'Post'), ('page', 'Page')], default='post', help_text='Select Page for semi-static pages. See docs for info.', max_length=6, verbose_name='Post or Page')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(blank=True, to='tangerine.Category')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelatedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=80)),
                ('site_url', models.URLField(null=True)),
                ('link_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['link_order'],
            },
        ),
        migrations.CreateModel(
            name='RelatedLinkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='relatedlink',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tangerine.RelatedLinkGroup'),
        ),
    ]
