# Generated by Django 2.1.dev20171104145028 on 2017-11-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0010_config_auto_approve_previous_commentors'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP (v4 or v6) of the comment submitter.', null=True, verbose_name='IP Address'),
        ),
        migrations.AddField(
            model_name='comment',
            name='spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_agent',
            field=models.CharField(blank=True, help_text='Reported user-agent string of the comment submitter.', max_length=160),
        ),
        migrations.AddField(
            model_name='config',
            name='akismet_key',
            field=models.CharField(blank=True, help_text='For comment spam control (recommended) - get a free/donationware key from https://akismet.com', max_length=14),
        ),
        migrations.AddField(
            model_name='config',
            name='site_url',
            field=models.URLField(blank=True, help_text='Only required for Akismet spam checking'),
        ),
    ]
