# Generated by Django 2.0 on 2017-12-17 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0013_config_moderation_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Publication Date/Time'),
        ),
    ]
