# Generated by Django 2.0 on 2018-01-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0016_auto_20180104_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='show_future',
            field=models.BooleanField(default=False, help_text='If enabled, posts dated in the future appear immediately. Default is False (drip-date behavior).'),
        ),
    ]
