# Generated by Django 2.0 on 2018-01-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0019_auto_20180113_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorpage',
            old_name='author',
            new_name='user',
        ),
    ]
