# Generated by Django 2.0.1 on 2018-01-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0024_remove_config_site_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='site_title',
            field=models.CharField(default='Arbitrary Site Title', help_text='To be displayed in page header and as part of HTML title tag', max_length=140),
        ),
    ]
