# Generated by Django 2.0.1 on 2018-01-22 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0027_auto_20180121_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatedlinkgroup',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Each RelatedLinkGroup must be associated with a blog / named news site.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.Config'),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Each post must be associated with a blog / named news site.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tangerine.Config'),
        ),
    ]
