# Generated by Django 2.0.1 on 2018-01-23 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0029_category_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedlinkgroup',
            name='slug',
        ),
    ]
