# Generated by Django 2.0.1 on 2018-01-28 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tangerine', '0032_auto_20180123_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(blank=True, help_text='Each post must be associated with a blog / named news site.', null=True, on_delete=django.db.models.deletion.CASCADE, to='tangerine.Blog'),
        ),
    ]
