# Generated by Django 2.0b1 on 2017-10-28 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='subject',
        ),
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(blank=True, help_text="If present, overrides automatic 'created' datetime and will not be published until.", null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 10, 28, 8, 19, 10, 625686), unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Something', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.Category'),
        ),
    ]
