# Generated by Django 2.1.dev20171102013351 on 2017-11-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_misc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trashed',
            field=models.BooleanField(default=False, help_text='Trashed posts are removed from views but not deleted. For safety, Trash rather than Delete.'),
        ),
    ]
